name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: ./test.sh
